using System.Collections;
using System.Text.Json;
using System.Text.Json.Serialization;
using PureQL.CSharp.Model.ArrayTypes;
using PureQL.CSharp.Model.Serialization.Aggregates.Date;
using PureQL.CSharp.Model.Serialization.Aggregates.DateTime;
using PureQL.CSharp.Model.Serialization.Aggregates.Numeric;
using PureQL.CSharp.Model.Serialization.Aggregates.String;
using PureQL.CSharp.Model.Serialization.Aggregates.Time;
using PureQL.CSharp.Model.Serialization.Arithmetics;
using PureQL.CSharp.Model.Serialization.ArrayEqualities;
using PureQL.CSharp.Model.Serialization.ArrayParameters;
using PureQL.CSharp.Model.Serialization.ArrayReturnings;
using PureQL.CSharp.Model.Serialization.ArrayScalars;
using PureQL.CSharp.Model.Serialization.BooleanOperations;
using PureQL.CSharp.Model.Serialization.Comparisons;
using PureQL.CSharp.Model.Serialization.EachArithmetics;
using PureQL.CSharp.Model.Serialization.EachBooleanOperations;
using PureQL.CSharp.Model.Serialization.EachComparisons;
using PureQL.CSharp.Model.Serialization.EachDateArithmetics;
using PureQL.CSharp.Model.Serialization.EachDateTimeArithmetics;
using PureQL.CSharp.Model.Serialization.EachEqualities;
using PureQL.CSharp.Model.Serialization.EachTimeArithmetics;
using PureQL.CSharp.Model.Serialization.Equalities;
using PureQL.CSharp.Model.Serialization.Fields;
using PureQL.CSharp.Model.Serialization.Parameters;
using PureQL.CSharp.Model.Serialization.Returnings;
using PureQL.CSharp.Model.Serialization.Scalars;
using PureQL.CSharp.Model.Serialization.Types;
using PureQL.CSharp.Model.Types;

namespace PureQL.CSharp.Model.Serialization;

public sealed record PureQLConverters : IEnumerable<JsonConverter>
{
    public IEnumerator<JsonConverter> GetEnumerator()
    {
        yield return new JsonStringEnumConverter(JsonNamingPolicy.CamelCase);
        yield return new AndOperatorConverter();
        yield return new BooleanOperatorConverter();
        yield return new NotOperatorConverter();
        yield return new OrOperatorConverter();
        yield return new BooleanOperatorArgumentsConverter();
        yield return new BooleanOrArrayReturningConverter();
        yield return new EachAndOperatorConverter();
        yield return new EachOrOperatorConverter();
        yield return new EachNotOperatorConverter();
        yield return new EachBooleanEqualityConverter();
        yield return new EachNumberEqualityConverter();
        yield return new EachStringEqualityConverter();
        yield return new EachDateEqualityConverter();
        yield return new EachTimeEqualityConverter();
        yield return new EachDateTimeEqualityConverter();
        yield return new EachUuidEqualityConverter();
        yield return new EachEqualityConverter();
        yield return new EachNumberComparisonConverter();
        yield return new EachStringComparisonConverter();
        yield return new EachDateComparisonConverter();
        yield return new EachDateTimeComparisonConverter();
        yield return new EachTimeComparisonConverter();
        yield return new EachComparisonConverter();
        yield return new EachAddConverter();
        yield return new EachSubtractConverter();
        yield return new EachMultiplyConverter();
        yield return new EachDivideConverter();
        yield return new EachArithmeticConverter();
        yield return new EachDateAddDaysConverter();
        yield return new EachDateDiffDaysConverter();
        yield return new EachDateTimeAddSecondsConverter();
        yield return new EachDateTimeDiffSecondsConverter();
        yield return new EachTimeAddSecondsConverter();
        yield return new EachTimeDiffSecondsConverter();
        yield return new NumberReturningOrArrayConverter();
        yield return new StringReturningOrArrayConverter();
        yield return new DateReturningOrArrayConverter();
        yield return new TimeReturningOrArrayConverter();
        yield return new DateTimeReturningOrArrayConverter();
        yield return new UuidReturningOrArrayConverter();
        yield return new BooleanEqualityConverter();
        yield return new DateEqualityConverter();
        yield return new DateTimeEqualityConverter();
        yield return new SingleValueEqualityConverter();
        yield return new NumberEqualityConverter();
        yield return new StringEqualityConverter();
        yield return new TimeEqualityConverter();
        yield return new UuidEqualityConverter();
        yield return new ArrayEqualityConverter();
        yield return new BooleanArrayEqualityConverter();
        yield return new DateArrayEqualityConverter();
        yield return new DateTimeArrayEqualityConverter();
        yield return new NumberArrayEqualityConverter();
        yield return new StringArrayEqualityConverter();
        yield return new TimeArrayEqualityConverter();
        yield return new UuidArrayEqualityConverter();
        yield return new NullFieldConverter();
        yield return new BooleanFieldConverter();
        yield return new DateFieldConverter();
        yield return new DateTimeFieldConverter();
        yield return new FieldConverter();
        yield return new NumberFieldConverter();
        yield return new StringFieldConverter();
        yield return new TimeFieldConverter();
        yield return new UuidFieldConverter();
        yield return new BooleanParameterConverter();
        yield return new DateParameterConverter();
        yield return new DateTimeParameterConverter();
        yield return new NullParameterConverter();
        yield return new NumberParameterConverter();
        yield return new StringParameterConverter();
        yield return new TimeParameterConverter();
        yield return new UuidParameterConverter();
        yield return new BooleanReturningConverter();
        yield return new DateReturningConverter();
        yield return new DateTimeReturningConverter();
        yield return new NumberReturningConverter();
        yield return new StringReturningConverter();
        yield return new TimeReturningConverter();
        yield return new UuidReturningConverter();
        yield return new BooleanScalarConverter();
        yield return new DateScalarConverter();
        yield return new DateTimeScalarConverter();
        yield return new NullScalarConverter();
        yield return new NumberScalarConverter();
        yield return new StringScalarConverter();
        yield return new TimeScalarConverter();
        yield return new UuidScalarConverter();
        yield return new DateComparisonConverter();
        yield return new DateTimeComparisonConverter();
        yield return new NumberComparisonConverter();
        yield return new StringComparisonConverter();
        yield return new TimeComparisonConverter();
        yield return new ComparisonConverter();
        yield return new AddConverter();
        yield return new SubtractConverter();
        yield return new MultiplyConverter();
        yield return new DivideConverter();
        yield return new ArithmeticConverter();
        yield return new MaxDateConverter();
        yield return new MinDateConverter();
        yield return new AverageDateConverter();
        yield return new DateAggregateConverter();
        yield return new AverageDateTimeConverter();
        yield return new MinDateTimeConverter();
        yield return new MaxDateTimeConverter();
        yield return new DateTimeAggregateConverter();
        yield return new CountConverter();
        yield return new MinNumberConverter();
        yield return new MaxNumberConverter();
        yield return new AverageNumberConverter();
        yield return new SumNumberConverter();
        yield return new NumberAggregateConverter();
        yield return new MaxStringConverter();
        yield return new MinStringConverter();
        yield return new StringAggregateConverter();
        yield return new AverageTimeConverter();
        yield return new MaxTimeConverter();
        yield return new MinTimeConverter();
        yield return new FromExpressionConverter();
        yield return new TimeAggregateConverter();
        yield return new OrderByItemConverter();
        yield return new JoinConverter();
        yield return new PaginationConverter();
        yield return new SelectExpressionConverter();
        yield return new QueryConverter();
        yield return new TypeConverter<BooleanType>();
        yield return new TypeConverter<DateType>();
        yield return new TypeConverter<DateTimeType>();
        yield return new TypeConverter<NullType>();
        yield return new TypeConverter<NumberType>();
        yield return new TypeConverter<StringType>();
        yield return new TypeConverter<TimeType>();
        yield return new TypeConverter<UuidType>();
        yield return new TypeConverter<BooleanArrayType>();
        yield return new TypeConverter<DateArrayType>();
        yield return new TypeConverter<DateTimeArrayType>();
        yield return new TypeConverter<NullArrayType>();
        yield return new TypeConverter<NumberArrayType>();
        yield return new TypeConverter<StringArrayType>();
        yield return new TypeConverter<TimeArrayType>();
        yield return new TypeConverter<UuidArrayType>();
        yield return new BooleanArrayScalarConverter();
        yield return new DateArrayScalarConverter();
        yield return new DateTimeArrayScalarConverter();
        yield return new NullArrayScalarConverter();
        yield return new NumberArrayScalarConverter();
        yield return new StringArrayScalarConverter();
        yield return new TimeArrayScalarConverter();
        yield return new UuidArrayScalarConverter();
        yield return new BooleanArrayParameterConverter();
        yield return new DateArrayParameterConverter();
        yield return new DateTimeArrayParameterConverter();
        yield return new NullArrayParameterConverter();
        yield return new NumberArrayParameterConverter();
        yield return new StringArrayParameterConverter();
        yield return new TimeArrayParameterConverter();
        yield return new UuidArrayParameterConverter();
        yield return new BooleanArrayReturningConverter();
        yield return new DateArrayReturningConverter();
        yield return new DateTimeArrayReturningConverter();
        yield return new NumberArrayReturningConverter();
        yield return new StringArrayReturningConverter();
        yield return new TimeArrayReturningConverter();
        yield return new UuidArrayReturningConverter();
        yield return new ArrayReturningConverter();
        yield return new SingleValueReturningConverter();
        yield return new EqualityConverter();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }
}
